version: "3"
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_AUTH_METHOD=md5
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db:/var/lib/postgresql/data
 
volumes:
  db:
    driver: local
