services:
  amqp:
    image: rabbitmq:latest
    hostname: maestro-rabbit
    restart: always
    ports:
      - 5672:5672
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_AUTH_METHOD=md5
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - maestro-pg:/var/lib/postgresql/data

volumes:
  maestro-pg:
    driver: local
