package db

import (
	"database/sql"
	"fmt"
)

// Returns the ID generated by the database for this search
func CreateSearch(db *sql.DB, videoSearchQuery string, userId int64) (int64, error) {
	// TODO: Start here
	statement := fmt.Sprintf(
		`insert into search (query, user_id) values("%s", %d);`,
		videoSearchQuery, userId,
	)
	var result sql.Result
	result, err = db.Exec(statement)

	if err != nil {
		return 0, nil
	}

	var searchId int64
	searchId, err = result.LastInsertId()

	if err != nil {
		return 0, nil
	}

	return searchId, nil
}
