package db

import (
	"database/sql"
	"fmt"

	"github.com/google/uuid"
)

// Returns the ID generated by the database for this search
func CreateSearch(db *sql.DB, videoSearchQuery string, userId string) (string, error) {
	searchId := uuid.NewString()
	statement := fmt.Sprintf(
		`insert into search (id, query, app_user_id) values('%s', '%s', '%s');`,
		searchId, videoSearchQuery, userId,
	)
	_, err = db.Exec(statement)

	if err != nil {
		return "", err
	}

	return searchId, nil
}
